=== SAP/abap-file-formats/file-formats/suso/suso-v1.json
{
  "$comment": "This file is autogenerated, do not edit manually, see https://github.com/SAP/abap-file-formats for more information.",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/SAP/abap-file-formats/blob/main/file-formats/suso/suso-v1.json",
  "title": "Authorization Object",
  "description": "Authorization object",
  "type": "object",
  "properties": {
    "formatVersion": {
      "title": "Format Version",
      "description": "Format version",
      "type": "string",
      "const": "1"
    },
    "header": {
      "title": "Header",
      "description": "Header",
      "type": "object",
      "properties": {
        "description": {
          "title": "Description",
          "description": "Description of the ABAP object",
          "type": "string",
          "maxLength": 60
        },
        "originalLanguage": {
          "title": "Original Language",
          "description": "Original language of the ABAP object",
          "type": "string",
          "minLength": 2
        },
        "abapLanguageVersion": {
          "title": "ABAP Language Version",
          "description": "ABAP language version",
          "type": "string",
          "enum": [
            "standard",
            "keyUser",
            "cloudDevelopment"
          ],
          "enumTitles": [
            "Standard",
            "ABAP for Key Users",
            "ABAP Cloud Development"
          ],
          "enumDescriptions": [
            "Standard",
            "ABAP for key user extensibility",
            "ABAP cloud development"
          ],
          "default": "standard"
        }
      },
      "additionalProperties": false,
      "required": [
        "description",
        "originalLanguage"
      ]
    },
    "generalInformation": {
      "title": "General Information",
      "description": "General information",
      "type": "object",
      "properties": {
        "objectClass": {
          "title": "Object Class",
          "description": "Name of the authorization object class with a length of up to four characters. An authorization object class contains authorization objects from a given application area. Every object is assigned to exactly one class. This assignment has no functional meaning. It is required however in order to display an object in role maintenance. For authorization objects with ABAP language version 'ABAP for Cloud Development', the authorization object class will be set to 'CPAE' and cannot be changed. Caution: Authorization objects that should not be used any more, regardless of which application area they are from, should be assigned to object class 'AAAA' (obsolete authorization objects). This only applies to authorization objects with ABAP language version 'Standard ABAP'.",
          "type": "string",
          "maxLength": 4
        }
      },
      "additionalProperties": false,
      "required": [
        "objectClass"
      ]
    },
    "authorizationFields": {
      "title": "Authorization Fields",
      "description": "Authorization fields",
      "type": "array",
      "maxItems": 10,
      "items": {
        "title": "Authorization Fields",
        "description": "Authorization fields",
        "type": "object",
        "properties": {
          "authorizationField": {
            "title": "Authorization Field",
            "description": "Name of the authorization field. An authorization object can contain up to 10 authorization fields.",
            "type": "string",
            "maxLength": 10
          },
          "isActivityField": {
            "title": "Activity Field",
            "description": "By selecting this option, an authorization field can be flagged that can contain activity-related values. The ACTVT field is always an activity field. Organizational levels always represent organizational responsibilities, but never activities. Therefore, they cannot be declared as activity fields. If fields do not have a search help, it is very difficult to tell whether or not they can contain activity-related values. Therefore, they cannot be declared as activity fields. This field is only relevant in cloud systems.",
            "type": "boolean"
          },
          "searchHelp": {
            "title": "Search Help",
            "description": "If the search help for the authorization field returns unsuitable selection results in the current authorization object, an alternative search help can be maintained for the field, in order to select suitable values for the object/field combination. This object/field search help always has priority over the search help for the field.",
            "type": "string",
            "maxLength": 30
          }
        },
        "additionalProperties": false,
        "required": [
          "authorizationField"
        ]
      }
    },
    "permittedActivities": {
      "title": "Permitted Activities",
      "description": "Permitted activities. This structure is only relevant if one of the authorization fields is ACTVT or if one other authorization field is flagged as activity field.",
      "type": "array",
      "items": {
        "title": "Permitted Activities",
        "description": "Permitted activities can only be defined for authorization field ACTVT if it is contained in the authorization fields list or for authorization fields that are flagged as activity field.",
        "type": "object",
        "properties": {
          "activity": {
            "title": "Activity",
            "description": "Activity",
            "type": "string",
            "maxLength": 2
          },
          "accessCategory": {
            "title": "Access Category",
            "description": "The purpose is to store additional information directly on the authorization field about how the authorization object should be used when generating business roles. This classification is used during the generation of roles in order to generate roles that contain read authorizations only. This field is only relevant in cloud systems.",
            "type": "string",
            "enum": [
              "read",
              "write",
              "valueHelp"
            ],
            "enumTitles": [
              "Read",
              "Write",
              "Value Help"
            ],
            "enumDescriptions": [
              "Read",
              "Write",
              "Value help"
            ]
          }
        },
        "additionalProperties": false,
        "required": [
          "activity",
          "accessCategory"
        ]
      }
    },
    "objectAttributes": {
      "title": "Object Attributes",
      "description": "Object attributes",
      "type": "object",
      "properties": {
        "criticality": {
          "title": "Criticality",
          "description": "The classification in this field determines whether the default status of the authorization object can be set to 'No Authorization Check'. This default status is rejected for all objects that are considered to be critical. Authorization objects from the application areas Basis (S_*) and HR (P_* and PLOG*) are generally considered to be critical. Their classification cannot be changed. This also applies for objects that have already been delivered. For authorization objects with ABAP language version 'ABAP for Cloud Development', this function is not supported.",
          "type": "string",
          "enum": [
            "critical",
            "notCritical"
          ],
          "enumTitles": [
            "Critical",
            "Not Critical"
          ],
          "enumDescriptions": [
            "Critical",
            "Not critical"
          ]
        },
        "classCopyToDefaultData": {
          "title": "Classification for Copy to Default Data",
          "description": "When switching to change mode in transaction SU22 or press the 'Retrieve' button in the ADT editors for SUSH, SUSI or TRAN, all authorization objects that the authorization trace registered in the context of the application currently being processed and from the data model of the application (not available for all applications), are added to the object list if they are not already in it. Adding objects to the object list of any application does not make sense for all objects however. A condition can therefore be defined for adding objects or in order to prevent them from being added. For authorization objects with ABAP language version 'ABAP for Cloud Development', this function is not supported.",
          "type": "string",
          "enum": [
            "withoutRestriction",
            "ifInSameApplComponent",
            "ifInSameSoftwareComponent",
            "ifInSameSoftwarePackage",
            "notCopiedFromTraceData"
          ],
          "enumTitles": [
            "Without Restriction",
            "If Application and Object are in the same Application Component",
            "If Application and Object are in the same Software Component",
            "If Application and Object are in the same Software Package",
            "Not Copied from Trace Data"
          ],
          "enumDescriptions": [
            "Without restriction",
            "If application and object are in the same application component",
            "If application and object are in the same software component",
            "If application and object are in the same software package",
            "Not copied from trace data"
          ],
          "default": "withoutRestriction"
        }
      },
      "additionalProperties": false,
      "required": [
        "criticality"
      ]
    },
    "sapNewRelevance": {
      "title": "SAP New Relevance",
      "description": "SAP new relevance",
      "type": "object",
      "properties": {
        "isRelevantToSapNew": {
          "title": "Authorization Object is relevant to SAP_NEW",
          "description": "The role 'SAP_NEW' contains authorization objects that are checked additionally in a new release in existing applications. This ensures that users with SAP_NEW assignment will still be able to use their usual applications without authorization problems after an upgrade has taken place, and before the authorization default values and roles have been updated in transaction SU25, steps 2a to 2d. If the object being edited is used for additional authorization checks in existing applications, it is necessary to select the checkbox in order to mark the object as relevant for SAP_NEW. Otherwise the SAP_NEW role would be incomplete. For authorization objects with ABAP language version 'ABAP for Cloud Development', this function is not supported.",
          "type": "boolean"
        }
      },
      "additionalProperties": false
    },
    "classForCdsBdef": {
      "title": "Classification for ABAP CDS Behavior Definitions",
      "description": "Classification for ABAP CDS behavior definitions",
      "type": "object",
      "properties": {
        "usageInOwnAuthContext": {
          "title": "Usage in the OWN Authorization Context",
          "description": "In the header of a CDS behavior definition in a RAP business object, an OWN authorization context is specified using the statement define own authorization context. This statement documents which authorization objects are checked by the implementation of the RAP business object. Value is set automatically during creation of the authorization object or when an already existing authorization without a value for this field is edited. The explicit selection or change of this value is only possible in SAP internal systems and only in transaction SU21. For objects with ABAP language version 'ABAP for Cloud Development', no changes can be made.",
          "type": "string",
          "enum": [
            "notAllowed",
            "allowed",
            "inSameSoftwareComponent"
          ],
          "enumTitles": [
            "Not Allowed",
            "Allowed",
            "BDEF and authorization object in the same software component"
          ],
          "enumDescriptions": [
            "The authorization object must not be used in the OWN authorization context.",
            "The authorization object can be used in the OWN authorization context.",
            "The authorization object can be used in the OWN authorization context if the CDS behavior definition of the RAP business object and the authorization object both belong to the same software component."
          ]
        },
        "usageInPrivilegedBdefMode": {
          "title": "Usage in the privileged BDEF Mode",
          "description": "In the header part of a ABAP CDS behavior definition of a managed or unmanaged RAP business object, it is possible to specify 'with privileged mode disabling ContextName'. This causes authorization context 'ContextName' to be automatically disabled when a RAP business object consumer uses privileged access to the RAP business object in question. This classification defines whether an authorization object can be used in authorization context 'ContextName'. Value is set automatically during creation of the authorization object or when an already existing authorization without a value for this field is edited. The explicit selection or change of this value is only possible in SAP internal systems and only in transaction SU21. For objects with ABAP language version 'ABAP for Cloud Development', no changes can be made.",
          "type": "string",
          "enum": [
            "notAllowed",
            "allowed"
          ],
          "enumTitles": [
            "Not Allowed",
            "Allowed"
          ],
          "enumDescriptions": [
            "Authorization object cannot be used in authorization context 'ContextName'. Critical authorization objects are automatically set to this value.",
            "Authorization object can be used in authorization context 'ContextName'."
          ]
        }
      },
      "additionalProperties": false,
      "required": [
        "usageInOwnAuthContext",
        "usageInPrivilegedBdefMode"
      ]
    }
  },
  "additionalProperties": false,
  "required": [
    "formatVersion",
    "header"
  ]
}

=== SAP/abap-file-formats/file-formats/suso/examples/z_aff_example_suso_2.suso.json
{
  "formatVersion": "1",
  "header": {
    "description": "Test Object Cloud",
    "originalLanguage": "en",
    "abapLanguageVersion": "cloudDevelopment"
  },
  "generalInformation": {
    "objectClass": "CPAE"
  },
  "authorizationFields": [
    {
      "authorizationField": "ACTVT",
      "isActivityField": true
    }
  ],
  "permittedActivities": [
    {
      "activity": "03",
      "accessCategory": "read"
    }
  ],
  "objectAttributes": {
    "criticality": "notCritical"
  },
  "classForCdsBdef": {
    "usageInOwnAuthContext": "allowed",
    "usageInPrivilegedBdefMode": "allowed"
  }
}
