=== SAP/abap-file-formats/file-formats/sush/sush-v1.json
{
  "$comment": "This file is autogenerated, do not edit manually, see https://github.com/SAP/abap-file-formats for more information.",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/SAP/abap-file-formats/blob/main/file-formats/sush/sush-v1.json",
  "title": "Authorization Default Properties",
  "description": "Authorization default (SUSH) properties",
  "type": "object",
  "properties": {
    "formatVersion": {
      "title": "Format Version",
      "description": "Format version",
      "type": "string",
      "const": "1"
    },
    "header": {
      "title": "Header",
      "description": "Header",
      "type": "object",
      "properties": {
        "description": {
          "title": "Description",
          "description": "Description of the ABAP object",
          "type": "string",
          "maxLength": 60
        },
        "originalLanguage": {
          "title": "Original Language",
          "description": "Original language of the ABAP object",
          "type": "string",
          "minLength": 2
        },
        "abapLanguageVersion": {
          "title": "ABAP Language Version",
          "description": "ABAP language version",
          "type": "string",
          "enum": [
            "standard",
            "cloudDevelopment"
          ],
          "enumTitles": [
            "Standard",
            "ABAP Cloud Development"
          ],
          "enumDescriptions": [
            "Standard",
            "ABAP cloud development"
          ],
          "default": "standard"
        }
      },
      "additionalProperties": false,
      "required": [
        "description",
        "originalLanguage"
      ]
    },
    "generalInformation": {
      "title": "General Information",
      "description": "General information",
      "type": "object",
      "properties": {
        "applicationName": {
          "title": "Application Name",
          "description": "Display name of the authorization default",
          "type": "string",
          "maxLength": 132
        },
        "applicationType": {
          "title": "Application Type",
          "description": "Object type of the authorization default",
          "type": "string",
          "maxLength": 80
        },
        "maintenanceMode": {
          "title": "Maintenance Mode",
          "description": "Maintenance modes for applications define how applications can be modified Used on on-premise systems only.",
          "type": "string",
          "enum": [
            "manual",
            "automatic",
            "automaticBasisObjects",
            "noDefaultValues",
            "deprecated",
            "obsolete"
          ],
          "enumTitles": [
            "Manual Maintenance",
            "Automatic Maintenance (All Objects)",
            "Automatic Maintenance (Basis Authorization Objects Only)",
            "Application Does Not Require Default Values",
            "Application Is Deprecated",
            "Application Is Obsolete"
          ],
          "enumDescriptions": [
            "This mode is appropriate as long as maintenance of default data has not been completed yet. New objects whose check has been detected by the authorization trace are added to the object list in change mode with the maintenance status Not maintained.",
            "In change mode, all authorization objects added from the authorization trace are automatically assigned the default status No Default.",
            "Only authorization objects from the application areas Basis (S_*) and HR (P_* and PLOG) are automatically added with the default status No Default. All other new objects are given the status Unmaintained, which must be changed.",
            "This modus is given to all applications for whose execution only the start authorization is required.",
            "It is used to classify applications that are not being developed any more but that can still be used. In the case of transactions, it is possible to designate successor transactions.",
            "This mode is used to classify applications that are not being developed any more and because of this do not meet important functional requirements or are not needed any more."
          ],
          "default": "manual"
        },
        "defaultValuesRequired": {
          "title": "Default Values Required",
          "description": "Indicates that no authorization defaults are defined. Used on cloud systems only.",
          "type": "string",
          "enum": [
            "yes",
            "no"
          ],
          "enumTitles": [
            "Yes",
            "No"
          ],
          "enumDescriptions": [
            "Default values are required",
            "Default values are not required"
          ],
          "default": "yes"
        },
        "documentation": {
          "title": "Documentation",
          "description": "Authorization defaults documentation for application.",
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "applicationName",
        "applicationType"
      ]
    },
    "authorizationObjects": {
      "title": "Authorization Objects",
      "description": "Authorization objects with maintenance status and field values",
      "type": "array",
      "items": {
        "title": "Authorization Object Details",
        "description": "Authorization default values define which authorization objects and field values are automatically proposed when creating roles, simplifying role maintenance and ensuring consistent security settings across users and roles.",
        "type": "object",
        "properties": {
          "authObjectName": {
            "title": "Object",
            "description": "Name of the authorization object",
            "type": "string",
            "maxLength": 10
          },
          "maintenanceStatus": {
            "title": "Maintenance Status",
            "description": "The maintenance status of an authorization object controls if AUTHORITY-CHECK runs for it in its application and whether an authorization default is added to a data of role by the profile generator when the app is in the role menu.",
            "type": "string",
            "enum": [
              "undefined",
              "noDefault",
              "defaultWithValues",
              "defaultWithoutValues",
              "inactiveValues",
              "noAuthorizationCheck"
            ],
            "enumTitles": [
              "Undefined",
              "No Default",
              "Default With Field Values",
              "Default Without Field Values",
              "Default Inactive",
              "No Authorization Check"
            ],
            "enumDescriptions": [
              "The maintenance status is undefined and must be specified.",
              "This status is given to all objects that are not required for the execution of functions in the application. The authorization check is executed in exactly the same way the statuses described above.",
              "This default status is assigned to all objects that are used to protect functions within the associated application and for which the delivery of fixed values in one or more authorization fields would help to simplify authorization maintenance in roles.",
              "This status is suitable for objects whose authorizations are required for using an application, but all of whose authorization fields have to be maintained by the role administrator with customer-specific values.",
              "For objects with this status, the authorization check always returns the value sy-subrc = 0 regardless of which authorizations the user actually has. For objects belonging to the application areas Basis (S_*) and HR (P_* and PLOG), it is forbidden.",
              "No authorization check is performed for this object. Used on cloud systems only."
            ],
            "default": "defaultWithValues"
          },
          "documentation": {
            "title": "Documentation",
            "description": "Authorization default documentation for object",
            "type": "string"
          },
          "authObjectFieldValues": {
            "title": "Authorization Field Values",
            "description": "Authorization defaults authorization field value",
            "type": "array",
            "items": {
              "title": "Authorization Field Values",
              "description": "Authorization defaults authorization field value",
              "type": "object",
              "properties": {
                "authFieldName": {
                  "title": "Authorization Field",
                  "description": "Authorization field",
                  "type": "string",
                  "maxLength": 10
                },
                "authFieldLowValue": {
                  "title": "From",
                  "description": "From value",
                  "type": "string",
                  "maxLength": 40
                },
                "authFieldHighValue": {
                  "title": "To",
                  "description": "To value",
                  "type": "string",
                  "maxLength": 40
                }
              },
              "additionalProperties": false
            }
          }
        },
        "additionalProperties": false,
        "required": [
          "authObjectName"
        ]
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "formatVersion",
    "header",
    "generalInformation"
  ]
}

=== SAP/abap-file-formats/file-formats/sush/examples/Z_FM_AFF_EXAMPLE              RF.sush.json
{
  "formatVersion": "1",
  "header": {
    "description": "Test example for AFF",
    "originalLanguage": "en"
  },
  "generalInformation": {
    "applicationName": "Z_FM_AFF_EXAMPLE",
    "applicationType": "FUNC",
    "maintenanceMode": "manual",
    "defaultValuesRequired": "yes"    
  },
  "authorizationObjects": [
    {
      "authObjectName": "S_DEVELOP",
      "maintenanceStatus": "defaultWithValues",
      "authObjectFieldValues": [
        {
          "authFieldName": "DEVCLASS"
        },
        {
          "authFieldName": "OBJTYPE"
        },
        {
          "authFieldName": "OBJNAME"
        },
        {
          "authFieldName": "P_GROUP"
        },
        {
          "authFieldName": "ACTVT",
          "authFieldLowValue": "03"
        }
      ]
    },
    {
      "authObjectName": "S_RFC",
      "maintenanceStatus": "noDefault"
    }
  ]
}

=== SAP/abap-file-formats/file-formats/sush/examples/0EAF320E91BD2A6A7209F7C1CCCCC2HT.json
{
  "formatVersion": "1",
  "header": {
    "description": "R3TR HTTP AFF_EXAMPLE_FOR_SUSH",
    "originalLanguage": "en",
    "abapLanguageVersion": "cloudDevelopment"
  },
  "generalInformation": {
    "applicationName": "AFF_EXAMPLE_FOR_SUSH",
    "applicationType": "HTTP",
    "maintenanceMode": "manual",
    "defaultValuesRequired": "yes"
  },
  "authorizationObjects": [
    {
      "authObjectName": "S_AUTH_DEV",
      "maintenanceStatus": "inactiveValues",
      "authObjectFieldValues": [
        {
          "authFieldName": "ACTVT"
        }
      ]
    },
    {
      "authObjectName": "S_START",
      "maintenanceStatus": "noDefault"
    },
    {
      "authObjectName": "S_TABU_NAM",
      "maintenanceStatus": "defaultWithValues",
      "authObjectFieldValues": [
        {
          "authFieldName": "ACTVT",
          "authFieldLowValue": "03"
        },
        {
          "authFieldName": "TABLE"
        }
      ]
    }
  ]
}

=== SAP/abap-file-formats/file-formats/sush/examples/z_aff_example_sush.sush.json
{
  "formatVersion": "1",
  "header": {
    "description": "R3TR SUCO ADT_SUSH_SRV",
    "originalLanguage": "de"
  },
  "generalInformation": {
    "applicationName": "ADT_SUSH_SRV",
    "applicationType": "SUCO",
    "maintenanceMode": "manual"
  },
  "authorizationObjects": [
    {
      "authObjectName": "S_ABAPDUMP",
      "maintenanceStatus": "noDefault"
    },
    {
      "authObjectName": "S_ABPLNGVS",
      "maintenanceStatus": "defaultWithoutValues"
    },
    {
      "authObjectName": "S_ADT_RES",
      "maintenanceStatus": "defaultWithValues",
      "authObjectFieldValues": [
        {
          "authFieldName": "URI",
          "authFieldLowValue": "/sap/bc/adt/aps/iam/sush"
        },
        {
          "authFieldName": "URI",
          "authFieldLowValue": "/sap/bc/adt/aps/iam/sush/*"
        }
      ]
    },
    {
      "authObjectName": "S_ALV_LAYO",
      "maintenanceStatus": "noDefault"
    },
    {
      "authObjectName": "S_ALV_LAYR",
      "maintenanceStatus": "noDefault"
    },
    {
      "authObjectName": "S_APPL_LOG",
      "maintenanceStatus": "noDefault"
    },
    {
      "authObjectName": "S_DATASET",
      "maintenanceStatus": "noDefault"
    },
    {
      "authObjectName": "S_DEVELOP",
      "maintenanceStatus": "defaultWithValues",
      "authObjectFieldValues": [
        {
          "authFieldName": "DEVCLASS"
        },
        {
          "authFieldName": "OBJTYPE",
          "authFieldLowValue": "SUSH"
        },
        {
          "authFieldName": "OBJNAME"
        },
        {
          "authFieldName": "P_GROUP"
        },
        {
          "authFieldName": "ACTVT"
        }
      ]
    },
    {
      "authObjectName": "S_GUI",
      "maintenanceStatus": "noDefault"
    },
    {
      "authObjectName": "S_ICF_ADM",
      "maintenanceStatus": "noDefault"
    },
    {
      "authObjectName": "S_PACKSTRU",
      "maintenanceStatus": "noDefault"
    },
    {
      "authObjectName": "S_SCOPE",
      "maintenanceStatus": "noDefault"
    },
    {
      "authObjectName": "S_SERVICE",
      "maintenanceStatus": "noDefault"
    },
    {
      "authObjectName": "S_SYS_INFO",
      "maintenanceStatus": "noDefault"
    },
    {
      "authObjectName": "S_TABU_DIS",
      "maintenanceStatus": "noDefault"
    },
    {
      "authObjectName": "S_TABU_NAM",
      "maintenanceStatus": "noDefault"
    },
    {
      "authObjectName": "S_TCODE",
      "maintenanceStatus": "noDefault"
    },
    {
      "authObjectName": "S_TRANSPRT",
      "maintenanceStatus": "noDefault"
    }
  ]
}
